REFLNS = [
    "entry_id", "observed_criterion_sigma_I", "observed_criterion_sigma_F", 
    "d_resolution_low", "d_resolution_high", "number_obs", "number_all", 
    "percent_possible_obs", "pdbx_Rmerge_I_obs", "pdbx_Rsym_value", 
    "pdbx_netI_over_sigmaI", "B_iso_Wilson_estimate", "pdbx_redundancy", 
    "R_free_details", "limit_h_max", "limit_h_min", "limit_k_max", 
    "limit_k_min", "limit_l_max", "limit_l_min", "observed_criterion_F_max", 
    "observed_criterion_F_min", "pdbx_chi_squared", "pdbx_scaling_rejects", 
    "pdbx_diffrn_id", "pdbx_ordinal", 
]

REFINE = [
    "entry_id", "ls_number_reflns_obs", "ls_number_reflns_all",
    "pdbx_ls_sigma_I", "pdbx_ls_sigma_F", "pdbx_data_cutoff_high_absF",
    "pdbx_data_cutoff_low_absF", "ls_d_res_low", "ls_d_res_high",
    "ls_percent_reflns_obs", "ls_R_factor_obs", "ls_R_factor_all",
    "ls_R_factor_R_work", "ls_R_factor_R_free", "ls_R_factor_R_free_error",
    "ls_R_factor_R_free_error_details", "ls_percent_reflns_R_free",
    "ls_number_reflns_R_free", "ls_number_parameters", "ls_number_restraints",
    "occupancy_min", "occupancy_max", "correlation_coeff_Fo_to_Fc",
    "correlation_coeff_Fo_to_Fc_free", "B_iso_mean", "aniso_B[1][1]",
    "aniso_B[2][2]", "aniso_B[3][3]", "aniso_B[1][2]", "aniso_B[1][3]",
    "aniso_B[2][3]", "solvent_model_details", "solvent_model_param_ksol",
    "solvent_model_param_bsol", "pdbx_solvent_vdw_probe_radii",
    "pdbx_solvent_ion_probe_radii", "pdbx_solvent_shrinkage_radii",
    "pdbx_ls_cross_valid_method", "details", "pdbx_starting_model",
    "pdbx_method_to_determine_struct", "pdbx_isotropic_thermal_model",
    "pdbx_stereochemistry_target_values",
    "pdbx_stereochem_target_val_spec_case", "pdbx_R_Free_selection_details",
    "pdbx_overall_ESU_R_Free", "overall_SU_B", "ls_redundancy_reflns_obs",
    "B_iso_min", "B_iso_max", "overall_SU_R_Cruickshank_DPI",
    "overall_SU_R_free", "overall_SU_ML", "pdbx_overall_ESU_R",
    "pdbx_data_cutoff_high_rms_absF", "pdbx_refine_id",
    "pdbx_overall_phase_error", "ls_wR_factor_R_free",
    "ls_wR_factor_R_work", "overall_FOM_free_R_set", "overall_FOM_work_R_set",
    "pdbx_diffrn_id", "pdbx_TLS_residual_ADP_flag",
    "pdbx_overall_SU_R_free_Cruickshank_DPI", "pdbx_overall_SU_R_Blow_DPI",
    "pdbx_overall_SU_R_free_Blow_DPI",
]